### ISSUE TITLE
No output produced

### ISSUE THREAD

**Issue by lt11** [gkanogiannis/fastreeR#3]
Hi,

My calculations with vcf2dist are stuck here:

````
cpus=16
using=16
2023/08/25 14:07:24 VCFManager: START READ
16777216
2023/08/25 14:07:25 VariantProcessor: 15        50000
2023/08/25 14:07:26 VariantProcessor: 8 100000
2023/08/25 14:07:26 VariantProcessor: 12        150000
2023/08/25 14:07:26 VariantProcessor: 8 200000
2023/08/25 14:07:27 VariantProcessor: 4 250000
````

I was processing a large file (1.2 GB) with almost 1 million variants and 82 samples. 

Any suggestion?

Thanks for your help.

Best,

Lorenzo

**Comment by gkanogiannis** [comment]
Hi Lorenzo,

This indicates that not enough RAM is allocated to JVM for parsing all your variants and hence it is stuck at 250k of them.
How much RAM are you giving to the JVM? 

Use options(java.parameters="-Xmx8G") for example to give it 8G. This command has to be the first one in your script and on a fresh R session. Let me know how it goes. 

Regards,
Anestis

**Comment by lt11** [comment]
Hi Anestis,

It worked. Also, I run the script from a markdown, e.g. with ```R -e "rmarkdown::render('sg-eval.Rmd')"``` and still it worked. Thanks a lot!

Best,

Lorenzo
